In [2]:
import torch
import torch.nn.functional as F 
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self,X):
        return X-X.mean()

layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
# 把层作为组件合并到构建更复杂的模型中
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y=net(torch.rand(4,8))
Y.mean()

tensor(8.3819e-09, grad_fn=<MeanBackward0>)

In [4]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()# 调用参数的parameter类
        # 通过nn.Parameter来定义带参数的图层
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))
    def forward(self,X):   # weight 和X做矩阵乘法
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)
dense=MyLinear(5,3)# dense layer 全连接层
dense.weight



Parameter containing:
tensor([[ 2.0378e+00, -1.4792e+00,  1.7621e+00],
        [ 5.1205e-01,  6.4793e-01, -5.9422e-01],
        [-4.6629e-01, -1.6097e+00,  2.3289e-02],
        [-1.6288e-04, -4.0943e-01, -1.0763e+00],
        [ 1.7702e+00, -4.5050e-02, -8.3656e-01]], requires_grad=True)

In [5]:
# 用自定义层直接执行正向传播计算
dense(torch.rand(2,5))


tensor([[1.5672, 0.0000, 0.0000],
        [1.9985, 0.0000, 0.0000]])

In [6]:
# 使用自定义层构建模型
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.4965],
        [2.7531]])

In [ ]:
# 读写文件

import torch

from torch import nn