In [1]:
import torch 
from torch import nn
from d2l import torch as d2l


def pool2d(X, pool_size, mode='max'):
    # 定义函数pool2d，参数为X（输入数据）、pool_size（池化窗口大小）、mode（池化模式，默认为最大池化'max'）。
    # pool2d: 池化二维数据（pool是池化的缩写，2d是二维的缩写，2-dimensional）。
    
    p_h, p_w = pool_size
    # 将池化窗口大小（pool_size）分别赋值给p_h（池化高度）和p_w（池化宽度）。
    
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    # 创建一个与输入数据X尺寸相关的全零矩阵Y，用于存储池化结果。
    # X.shape[0]和X.shape[1]分别是X的行数和列数。这个语句的意思是：Y的尺寸为(X的行数 - 池化窗口高度 + 1, X的列数 - 池化窗口宽度 + 1)。
    
    for i in range(Y.shape[0]):
        # 遍历Y的每一行i。
        
        for j in range(Y.shape[1]):
            # 遍历Y的每一列j。
            
            if mode == 'max':
                # 如果池化模式为最大池化（max pooling）。
                
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
                # 对输入数据X中从第i行开始、池化窗口大小为p_h行和p_w列的子矩阵进行最大值操作，并将结果赋值给Y的第i行第j列。
                
            elif mode == 'avg':
                # 如果池化模式为平均池化（average pooling）。
                
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
                # 对输入数据X中从第i行开始、池化窗口大小为p_h行和p_w列的子矩阵进行平均值操作，并将结果赋值给Y的第i行第j列。
                
    return Y
    # 返回池化结果Y。


In [3]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]) 
 # 定义一个3x3的二维张量X，使用torch.tensor创建。X的值为浮点数矩阵。
# X：输入数据，矩阵形式 

pool2d(X, (2, 2))
 # 调用之前定义的pool2d函数，传入X作为输入数据，(2, 2)作为池化窗口大小。
# pool2d: 二维池化函数，参数X是输入张量，(2, 2)是池化窗口的大小，高度和宽度均为2。


tensor([[4., 5.],
        [7., 8.]])

In [4]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [5]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [6]:
pool2d = nn.MaxPool2d(3)
# 使用nn模块中的MaxPool2d函数定义一个池化操作对象pool2d，池化窗口大小为3。
# MaxPool2d：最大池化二维（Max Pooling 2-dimensional），执行最大池化操作。
# pool2d：池化对象，用于执行最大池化。

pool2d(X)
# 对输入的张量X进行最大池化操作，使用3x3的窗口。
# X：输入数据，进行池化操作的输入张量。


tensor([[[[10.]]]])

In [7]:
#            窗口大小3*3
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [8]:
#                   窗口大小2*3
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [9]:
# 双通道
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [10]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])