In [1]:
!nvidia-smi

Wed Sep 25 01:07:14 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:04:00.0 Off |                  N/A |
| 40%   67C    P2   257W / 250W |   7733MiB / 11264MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:05:00.0 Off |                  N/A |
| 22%   

In [2]:
import torch
#得指定在gpu上 才会用gpu运算
from torch import nn# cuda不是gpu   第0个gpu      第1个gpu
torch.device('cpu'),torch.cuda.device('cuda'),torch.cuda.device('cuda:1')



(device(type='cpu'),
 <torch.cuda.device at 0x7f433dc15fd0>)

In [3]:
torch.cuda.device_count()

9

In [4]:
def try_gpu(i=0):
    """如果存在 就返回gpu(i) 如果不存在就返回cpu()"""
    if torch.cuda.device_count()>=i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    """返回所有可用的GPU 如果没有GPU 则返回[cpu(),]"""
    devices=[torch.device(f'cuda:{i}')for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(),try_gpu(10),try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0),
  device(type='cuda', index=1),
  device(type='cuda', index=2),
  device(type='cuda', index=3),
  device(type='cuda', index=4),
  device(type='cuda', index=5),
  device(type='cuda', index=6),
  device(type='cuda', index=7),
  device(type='cuda', index=8)])

In [5]:
# 查询张量所在的设备
x=torch.tensor([1,2,3])
x.device# 默认放在cpu上

device(type='cpu')

In [6]:
X=torch.ones(2,3,device=try_gpu())
X# 放在GPU 上  device='cuda；0'

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [7]:
Y=torch.rand(2,3,device=try_gpu(1))
Y#放在GPU 上  device='cuda；1'

tensor([[0.6545, 0.8756, 0.2873],
        [0.2081, 0.3641, 0.6087]], device='cuda:1')

In [8]:
z=X.cuda(1)
print(X)#而且必须放在同一个GPU上
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


NameError: name 'Z' is not defined

In [ ]:
Y+Z

NameError: name 'Z' is not defined

In [ ]:
Z.cuda(1)is Z

In [ ]:
net = nn.Sequential(nn.Linear(3, 1))#神经网络模型也可以只当设备
net = net.to(device=try_gpu())

In [ ]:
net(X)

In [ ]:
net[0].weight.data.device# 模型参数都存储在同一个GPU上