In [7]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x-y,x/y,x*y,x**y

(tensor([5.]), tensor([1.]), tensor([1.5000]), tensor([6.]), tensor([9.]))

In [9]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [10]:
x[3]

tensor(3)

In [11]:
len(x)

4

In [12]:
x.shape

torch.Size([4])

In [13]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [14]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [15]:
B=torch.tensor([[1,2,3,],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [18]:
B.T#B的转置


tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [27]:
X=torch.arange(64).reshape(2,4,8)
X

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29, 30, 31]]])

In [30]:
X=torch.arange(64).reshape(2,8,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47],
         [48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]])

In [31]:
X=torch.arange(64).reshape(8,4,2)
X

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35],
         [36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53],
         [54, 55]],

        [[56, 57],
         [58, 59],
         [60, 61],
         [62, 63]]])

In [26]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()# 分配新内存，把A的一个副本给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [32]:
# Hadamard Product
A*B#按元素乘

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [34]:
a=2
X=torch.arange(24).reshape(2,3,4)
X+a#每个元素都加a

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [35]:
x,x.sum()

(tensor([0, 1, 2, 3]), tensor(6))

In [42]:
X,X.shape
X_sum_axis0=X.sum(axis=0)
X_sum_axis0,X_sum_axis0.shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [41]:
X_sum_axis1=X.sum(axis=1)
X_sum_axis1,X_sum_axis1.shape

(tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [46]:
X = torch.arange(24).reshape(2, 3, 4).float()

X.mean(),X.sum()/X.numel()# numel: number of elements

(tensor(11.5000), tensor(11.5000))

In [47]:
sum_A=A.sum(axis=1,keepdims=True)# keep dimension
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [48]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [49]:
A.cumsum(axis=0)  # 计算矩阵或张量 A 在指定轴上的累加和（cumulative sum）。

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [50]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [51]:
A.cumsum(axis=1) 

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

In [58]:
y=torch.ones(4,dtype=torch.float32)
x=torch.arange(4,dtype=torch.float32)
x,y,torch.dot(x,y)#dot  点积

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [59]:
x

tensor([0., 1., 2., 3.])

In [60]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [61]:
A.shape,x.shape,torch.mv(A,x)# 矩阵-向量乘法（matrix-vector multiplication）
# 这是 PyTorch 提供的专门用于矩阵乘以向量的函数。

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [67]:
B=torch.rand(4,3,dtype=torch.float32)
B

tensor([[0.0529, 0.5859, 0.8192],
        [0.0798, 0.3788, 0.9013],
        [0.3049, 0.6713, 0.6352],
        [0.0947, 0.9873, 0.0092]])

In [68]:
torch.mm(A,B)# （matrix-MATRIX multiplication）

tensor([[ 0.9738,  4.6832,  2.1993],
        [ 3.1033, 15.1762, 11.6589],
        [ 5.2329, 25.6693, 21.1184],
        [ 7.3624, 36.1623, 30.5780],
        [ 9.4920, 46.6553, 40.0375]])

In [69]:
#范数；向量或矩阵的长度
# L2范数是向量元素平方和的平方根
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [70]:
#L1范数：向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [71]:
#Frobunius norm :矩阵元素平方和的平方根
#把矩阵拉成一个向量，求向量的范数
torch.norm(torch.ones((4,9)))

tensor(6.)

按特定轴求和
shape:[5,4]
axis:  0,1
axis=1  


In [76]:
PP=torch.arange(30).reshape(2,5,3)
PP

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],

        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]])

In [77]:
PP=torch.arange(48).reshape(2,4,6)
PP

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],

        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]]])

In [79]:
PP.sum().shape#标量

torch.Size([])

In [81]:
PP.sum(axis=0)

tensor([[24, 26, 28, 30, 32, 34],
        [36, 38, 40, 42, 44, 46],
        [48, 50, 52, 54, 56, 58],
        [60, 62, 64, 66, 68, 70]])

In [82]:
PP.sum(axis=1)

tensor([[ 36,  40,  44,  48,  52,  56],
        [132, 136, 140, 144, 148, 152]])

In [84]:
PP.sum(axis=1,keepdims=True).shape#keepdims:仍然还是三维

torch.Size([2, 1, 6])

In [85]:
print('9.范数')
u = torch.tensor([3.0, -4.0])
print('向量的𝐿2范数:', torch.norm(u))  # 向量的𝐿2范数
print('向量的𝐿1范数:', torch.abs(u).sum())  # 向量的𝐿1范数
v = torch.ones((4, 9))
print('v:', v)
print('矩阵的𝐿2范数:', torch.norm(v))  # 矩阵的𝐿2范数

9.范数
向量的𝐿2范数: tensor(5.)
向量的𝐿1范数: tensor(7.)
v: tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
矩阵的𝐿2范数: tensor(6.)


In [91]:
print('11.理解pytorch中的gather()函数')
a = torch.arange(15).view(3, 5)# 生成一个包含从 0 到 14 的张量，并将其重塑为形状为 (3, 5) 的二维张量。
print('11.1二维矩阵上gather()函数')
print('a:', a)
b = torch.zeros_like(a)# 创建一个与张量 a 形状相同的全零张量。
b[1][2] = 1  ##给指定索引的元素赋值
b[0][0] = 1  ##给指定索引的元素赋值
print('b:', b)
cc = a.gather(0, b)  # dim=0'
print('cc:', cc)
dd = a.gather(1, b)  # dim=1
print('dd:', dd)

11.理解pytorch中的gather()函数
11.1二维矩阵上gather()函数
a: tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
b: tensor([[1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0]])
cc: tensor([[5, 1, 2, 3, 4],
        [0, 1, 7, 3, 4],
        [0, 1, 2, 3, 4]])
dd: tensor([[ 1,  0,  0,  0,  0],
        [ 5,  5,  6,  5,  5],
        [10, 10, 10, 10, 10]])


In [92]:
print('11.2三维矩阵上gather()函数')
a = torch.randint(0, 30, (2, 3, 5))
print('a:', a)
index = torch.LongTensor([[[0, 1, 2, 0, 2],
                           [0, 0, 0, 0, 0],
                           [1, 1, 1, 1, 1]],
                          [[1, 2, 2, 2, 2],
                           [0, 0, 0, 0, 0],
                           [2, 2, 2, 2, 2]]])
print(a.size() == index.size())
b = torch.gather(a, 1, index)
print('b:', b)
c = torch.gather(a, 2, index)
print('c:', c)
index2 = torch.LongTensor([[[0, 1, 1, 0, 1],
                            [0, 1, 1, 1, 1],
                            [1, 1, 1, 1, 1]],
                           [[1, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0],
                            [1, 1, 0, 0, 0]]])
d = torch.gather(a, 0, index2)
print('d:', d)

11.2三维矩阵上gather()函数
a: tensor([[[22,  1,  4,  8, 29],
         [29, 16,  8,  7, 11],
         [ 4, 23, 17,  7, 23]],

        [[17,  0, 27, 11, 19],
         [27, 14, 29,  7,  0],
         [ 5, 24, 18,  0, 19]]])
True
b: tensor([[[22, 16, 17,  8, 23],
         [22,  1,  4,  8, 29],
         [29, 16,  8,  7, 11]],

        [[27, 24, 18,  0, 19],
         [17,  0, 27, 11, 19],
         [ 5, 24, 18,  0, 19]]])
c: tensor([[[22,  1,  4, 22,  4],
         [29, 29, 29, 29, 29],
         [23, 23, 23, 23, 23]],

        [[ 0, 27, 27, 27, 27],
         [27, 27, 27, 27, 27],
         [18, 18, 18, 18, 18]]])
d: tensor([[[22,  0, 27,  8, 19],
         [29, 14, 29,  7,  0],
         [ 5, 24, 18,  0, 19]],

        [[17,  1,  4,  8, 29],
         [29, 16,  8,  7, 11],
         [ 5, 24, 17,  7, 23]]])


In [94]:
print('12.理解pytorch中的max()和argmax()函数')
a = torch.tensor([[1, 2, 3], [3, 2, 1]])
b = a.argmax(1)
c = a.max(1)
d = a.max(1)[1]
print('a:', a)
print('a.argmax(1):', b)
print('a.max(1):', c)
print('a.max(1)[1]:', d)


12.理解pytorch中的max()和argmax()函数
a: tensor([[1, 2, 3],
        [3, 2, 1]])
a.argmax(1): tensor([2, 0])
a.max(1): torch.return_types.max(
values=tensor([3, 3]),
indices=tensor([2, 0]))
a.max(1)[1]: tensor([2, 0])


In [10]:
import torch
xx=torch.arange(5)
yy=torch.arange(5)
xx,yy,torch.dot(xx,yy)

# xxx=torch.arange(12).reshape(3,4)
# yyy=torch.arange(12).reshape(3,4)
# xxx,yyy,torch.dot(xxx,yyy)

#########torch.dot是计算两个一维张量间的点积
##就相当于权重和得分的相乘相加
##点积是相同位置按元素乘积的和

(tensor([0, 1, 2, 3, 4]), tensor([0, 1, 2, 3, 4]), tensor(30))

In [11]:
# 矩阵向量积
A=torch.arange(15).reshape(3,5)
x=torch.arange(5)
A,x,torch.mv(A,x)

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]),
 tensor([0, 1, 2, 3, 4]),
 tensor([ 30,  80, 130]))

In [ ]:

print('13.item()函数')
a = torch.Tensor([1, 2, 3])
print('a[0]:', a[0])  # 直接取索引返回的是tensor数据
print('a[0].item():', a[0].item())  # 获取python number

In [12]:
#标量

import torch
x=torch.tensor(3.0)
y=torch.tensor(2.0)
x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [13]:
#向量
x=torch.arange(7)
x

tensor([0, 1, 2, 3, 4, 5, 6])

In [14]:
x[4]

tensor(4)

In [15]:
len(x)


7

In [16]:
# 矩阵
A=torch.arange(12).reshape(3,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
A[1][3]

tensor(7)

In [19]:
A.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [21]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [23]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [24]:
A==A.T

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [28]:
C=torch.arange(24).reshape(2,3,4)
C

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [31]:
len(C)# len(C) 返回张量的第一个维度的大小，因为 len 函数在 PyTorch 中实际上返回的是张量的第一个维度的长度。

2

In [35]:
C.sum(axis=0),C.sum(axis=1),C.sum(axis=2)

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))