In [1]:
############上课
# 自动求导
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)
x.grad#x需要一个地方存梯度

In [3]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()#调用反向传播函数自动计算y关于x每个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad==4*x

tensor([True, True, True, True])

In [11]:
#在默认情况下，pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()#下划线表示重写
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [14]:
x.grad.zero_()
y=x*x#y不是标量 是点积后的向量
x,y

y.sum().backward()#机器学习很少对一个向量函数求导  一般对一个标量求导  sum后得到一个标量
x.grad

tensor([0., 2., 4., 6.])

In [16]:
# 把某些计算移动到记录的计算图之外
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x # u就是常数了
z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [18]:
##python控制流的梯度计算
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c


a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()
a.grad==d/a

tensor(True)

In [ ]:
#####################书上的

